### ISSUE TITLE
User help

### ISSUE THREAD

**Issue by konstantinmds** [rivoduck/wowzator#1]
Hi, can you give me some help,

 i have an application on the wowza streaming engine that looks like this:

[
![image](https://user-images.githubusercontent.com/28590354/152357295-d87061e2-d098-4380-8be9-d3203d82cdb2.png)
](url)

Is is possible from your application to get a json of a streaming object?

**Comment by rivoduck** [comment]
Hi, what do you mean by "streaming object"?
If you mean the configuration, you can use the Wowza REST API to get the configuration in XML, also from my tool you can get the configuration displayed interactively on the commandline (my tool takes it from Wowza using the REST API  and creates a Python object to represent the configuration of the Wowza Application)

If you mean something else (eg. the status of the stream such as details of the incoming and outgoing traffic on each application/instance/stream) then check the other Wowza REST API that give you this info.

My tool is meant to be a configuration manager so it does not look at status information.


Hope this helps!
Andrea

**Comment by konstantinmds** [comment]
I understand,

So basicaly my task is to recieve the data streamed for wowza and play it in the browser.
Do you have any resorces for that ?

also for the config.json file based on the photo above, is this config right ? 

```
	{
		"name": "testapp",
		"address": "199.76.12.161",
                 "stream": "tester",
		"user": "admin",
		"pw": "423234",
		"auth": "digest"
	}

**Comment by rivoduck** [comment]
The config file contains information about the servers, wowzator gets the config info through the Wowza REST API.
So the config file should be something like:
{
		"name": "name_of_server",
		"address": "199.76.12.161",
		"user": "admin",
		"pw": "423234",
		"auth": "digest"
	}
(the "stream" parameter is not needed...)

after version 4.8.5 wowza switched to basic auth instead of digest so you should set the "auth" field accordingly.
My tool does only show config info, so it tells you how the applications are set up, each application contains "instances" and "streams" that are created by the encoder and are not part of wowza configuration so they are not managed by wowzator.
There are REST APIs you can call to get info about active connections from viewers and from encoders.
Give a try to http://address:8086/connectioncounts for example but there are more APIs.
If you managed to set up wowzator, run it and do an "ls", you should see details about the server(s), I added a screenshot in the README file.

**Comment by rivoduck** [comment]
look at the Wowza REST API endpoint
address:8087/v2/machine/monitoring/current

this gives you the active applications with their instances and streams

**Comment by rivoduck** [comment]
This is more a generic question about the Wowzator functionalities and Wowza APIs in general, I am closing this ticket!
